import "server-only";

const escapeHtml = (value: string) => value.replace(/[&<>\"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '\"': "&quot;" })[c]!);
const siteUrl = () => (process.env.SITE_URL || "http://localhost:3000").replace(/\/$/, "");

export function renderNewsletterEmail(input: { body: string; productsText?: string | null; promoText?: string | null; ctaLabel?: string | null; ctaUrl?: string | null; unsubscribeUrl?: string | null }) {
  const paragraphs = input.body.trim().split(/\n\s*\n/).filter(Boolean).map(p => `<p style="margin:0 0 16px;color:#6E635D;font-size:15px;line-height:24px">${escapeHtml(p).replace(/\n/g, "<br>")}</p>`).join("");
  const products = (input.productsText || "").split(/\r?\n/).map(line => line.trim()).filter(Boolean).map(line => {
    const [name = "", description = "", price = "", link = ""] = line.split("|").map(part => part.trim());
    const safeLink = /^https?:\/\//i.test(link) ? link : "";
    return `<div style="border:1px solid #ECE3DC;border-radius:9px;background:#FCFAF8;padding:16px;margin:0 0 12px"><h3 style="margin:0 0 7px;color:#29201C;font-family:Georgia,serif;font-size:17px">${escapeHtml(name)}</h3>${description ? `<p style="margin:0 0 8px;color:#6E635D;font-size:13px;line-height:20px">${escapeHtml(description)}</p>` : ""}${price ? `<strong style="color:#B6492C">${escapeHtml(price)}</strong>` : ""}${safeLink ? `<p style="margin:12px 0 0"><a href="${escapeHtml(safeLink)}" style="color:#D47151;font-weight:bold">Ver producto →</a></p>` : ""}</div>`;
  }).join("");
  const promo = input.promoText?.trim() ? `<tr><td align="center" style="background:#D47151;padding:12px 20px;color:#fff;font-size:14px;font-weight:bold">${escapeHtml(input.promoText.trim())}</td></tr>` : "";
  const cta = input.ctaLabel?.trim() && input.ctaUrl?.trim() ? `<tr><td align="center" style="padding:8px 24px 30px"><a href="${escapeHtml(input.ctaUrl.trim())}" style="display:inline-block;background:#D47151;color:#fff;padding:13px 25px;border-radius:24px;text-decoration:none;font-size:14px;font-weight:bold">${escapeHtml(input.ctaLabel.trim())}</a></td></tr>` : "";
  const unsubscribe = input.unsubscribeUrl;
  const contact = process.env.NEXT_PUBLIC_EMAIL?.trim();
  const unsubscribeFooter = unsubscribe ? `Recibes este correo porque te suscribiste a las novedades de Chincol.<br><a href="${escapeHtml(unsubscribe)}" style="color:#C5B6AE;text-decoration:underline">Darte de baja</a>` : "Correo de prueba del newsletter de Chincol Artesanía.";
  return `<!doctype html><html lang="es"><body style="margin:0;background:#F4EFEB;font-family:Arial,Helvetica,sans-serif;color:#2D231E"><div style="display:none;max-height:0;overflow:hidden">Novedades de Chincol Artesanía</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#F4EFEB"><tr><td align="center" style="padding:24px 10px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:600px;background:#fff;border-radius:12px;overflow:hidden"><tr><td align="center" style="background:#29201C;padding:30px 20px"><div style="margin:auto auto 10px;background:#D47151;border-radius:50%;width:44px;height:44px;line-height:44px;color:#fff;font-size:22px">&#128038;</div><h1 style="margin:0 0 6px;color:#FAF6F0;font-family:Georgia,serif;font-size:25px;letter-spacing:1px">CHINCOL ARTESANÍA</h1><p style="margin:0;color:#C5B6AE;font-size:12px;letter-spacing:1px">OFICIO, TRADICIÓN · HECHO A MANO EN CHILE</p></td></tr>${promo}<tr><td style="padding:34px 30px 12px">${paragraphs}</td></tr>${products ? `<tr><td style="padding:0 24px 20px">${products}</td></tr>` : ""}${cta}<tr><td align="center" style="background:#29201C;padding:26px 20px;color:#9C8F87"><p style="margin:0 0 10px;color:#FAF6F0;font-family:Georgia,serif;font-weight:bold">Chincol Artesanía</p><p style="margin:0 0 14px;font-size:12px">Santiago, Chile · Envíos a todo el país</p><p style="margin:0 0 16px;font-size:12px"><a href="${siteUrl()}" style="color:#D47151;text-decoration:none">Visitar la página</a>${contact ? ` &nbsp;·&nbsp; <a href="mailto:${escapeHtml(contact)}" style="color:#D47151;text-decoration:none">Contacto</a>` : ""}</p><p style="margin:0;font-size:11px;line-height:17px">${unsubscribeFooter}</p></td></tr></table></td></tr></table></body></html>`;
}

export function newsletterBaseUrl() { return siteUrl(); }
